
export const NBA_TEAMS = [
  { id: 'ANY', name: 'Any Team', abbr: 'ANY' },
  { id: 'ATL', name: 'Atlanta Hawks', abbr: 'ATL' },
  { id: 'BOS', name: 'Boston Celtics', abbr: 'BOS' },
  { id: 'BKN', name: 'Brooklyn Nets', abbr: 'BKN' },
  { id: 'CHA', name: 'Charlotte Hornets', abbr: 'CHA' },
  { id: 'CHI', name: 'Chicago Bulls', abbr: 'CHI' },
  { id: 'CLE', name: 'Cleveland Cavaliers', abbr: 'CLE' },
  { id: 'DAL', name: 'Dallas Mavericks', abbr: 'DAL' },
  { id: 'DEN', name: 'Denver Nuggets', abbr: 'DEN' },
  { id: 'DET', name: 'Detroit Pistons', abbr: 'DET' },
  { id: 'GSW', name: 'Golden State Warriors', abbr: 'GSW' },
  { id: 'HOU', name: 'Houston Rockets', abbr: 'HOU' },
  { id: 'IND', name: 'Indiana Pacers', abbr: 'IND' },
  { id: 'LAC', name: 'LA Clippers', abbr: 'LAC' },
  { id: 'LAL', name: 'Los Angeles Lakers', abbr: 'LAL' },
  { id: 'MEM', name: 'Memphis Grizzlies', abbr: 'MEM' },
  { id: 'MIA', name: 'Miami Heat', abbr: 'MIA' },
  { id: 'MIL', name: 'Milwaukee Bucks', abbr: 'MIL' },
  { id: 'MIN', name: 'Minnesota Timberwolves', abbr: 'MIN' },
  { id: 'NOP', name: 'New Orleans Pelicans', abbr: 'NOP' },
  { id: 'NYK', name: 'New York Knicks', abbr: 'NYK' },
  { id: 'OKC', name: 'Oklahoma City Thunder', abbr: 'OKC' },
  { id: 'ORL', name: 'Orlando Magic', abbr: 'ORL' },
  { id: 'PHI', name: 'Philadelphia 76ers', abbr: 'PHI' },
  { id: 'PHX', name: 'Phoenix Suns', abbr: 'PHX' },
  { id: 'POR', name: 'Portland Trail Blazers', abbr: 'POR' },
  { id: 'SAC', name: 'Sacramento Kings', abbr: 'SAC' },
  { id: 'SAS', name: 'San Antonio Spurs', abbr: 'SAS' },
  { id: 'TOR', name: 'Toronto Raptors', abbr: 'TOR' },
  { id: 'UTA', name: 'Utah Jazz', abbr: 'UTA' },
  { id: 'WAS', name: 'Washington Wizards', abbr: 'WAS' },
];
